# Generated by Django 2.2 on 2021-11-27 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20211127_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
