# Generated by Django 2.2 on 2021-11-27 08:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipycomment',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
